package com.rouchtime.nlp.dao;

import com.rouchtime.nlp.model.NlpFinanceNewsNonRaw;
import java.util.List;

public interface NlpFinanceNewsNonRawMapper extends BaseRawMapper{


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nlp_finance_news_non_raw
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nlp_finance_news_non_raw
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    int insert(NlpFinanceNewsNonRaw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nlp_finance_news_non_raw
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    NlpFinanceNewsNonRaw selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nlp_finance_news_non_raw
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    List<NlpFinanceNewsNonRaw> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nlp_finance_news_non_raw
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    int updateByPrimaryKey(NlpFinanceNewsNonRaw record);


}