package com.rouchtime.nlp.model;

public class NlpFinanceNewsNonRaw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nlp_finance_news_non_raw.id
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nlp_finance_news_non_raw.news_key
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    private String newsKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nlp_finance_news_non_raw.title
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nlp_finance_news_non_raw.url
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nlp_finance_news_non_raw.label
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nlp_finance_news_non_raw.content
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nlp_finance_news_non_raw.id
     *
     * @return the value of nlp_finance_news_non_raw.id
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nlp_finance_news_non_raw.id
     *
     * @param id the value for nlp_finance_news_non_raw.id
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nlp_finance_news_non_raw.news_key
     *
     * @return the value of nlp_finance_news_non_raw.news_key
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public String getNewsKey() {
        return newsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nlp_finance_news_non_raw.news_key
     *
     * @param newsKey the value for nlp_finance_news_non_raw.news_key
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public void setNewsKey(String newsKey) {
        this.newsKey = newsKey == null ? null : newsKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nlp_finance_news_non_raw.title
     *
     * @return the value of nlp_finance_news_non_raw.title
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nlp_finance_news_non_raw.title
     *
     * @param title the value for nlp_finance_news_non_raw.title
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nlp_finance_news_non_raw.url
     *
     * @return the value of nlp_finance_news_non_raw.url
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nlp_finance_news_non_raw.url
     *
     * @param url the value for nlp_finance_news_non_raw.url
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nlp_finance_news_non_raw.label
     *
     * @return the value of nlp_finance_news_non_raw.label
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nlp_finance_news_non_raw.label
     *
     * @param label the value for nlp_finance_news_non_raw.label
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nlp_finance_news_non_raw.content
     *
     * @return the value of nlp_finance_news_non_raw.content
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nlp_finance_news_non_raw.content
     *
     * @param content the value for nlp_finance_news_non_raw.content
     *
     * @mbg.generated Tue Jul 25 18:05:45 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}